name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install and Build
        run: |
          bun install
          bun run build
        env:
          VITE_GITHUB_API_USER: ${{ secrets.VITE_GITHUB_API_USER }}
          VITE_GITHUB_API_URL: ${{ secrets.VITE_GITHUB_API_URL }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "github-pages"
          path: ./build

      - name: Deploy
        uses: actions/deploy-pages@v4
